### ISSUE TITLE
depth is set to -1

### ISSUE THREAD

**Issue by shimotori** [thinkwell/mongoid_nested_set#12]
I am using v0.2.0 (2ad8815da8).

When I create a child node or move a node, depths of others are set to -1.

I checked behaviors of some specs in mongoid_nested_set_spec.rb:

"can create a child node via children<<":

```
root.depth.should == 0  # got -1
```

"can move left":

```
@nodes[:slacks].depth.should == 3  # got -1
```

Please check the code.

**Comment by asavartsov** [comment]
According to my test that's shouldn't happen as far as depths are rebuilding right after move... Anyways I'll modify the move algorithm to not touch depth.

**Comment by asavartsov** [comment]
@shimotori Could you test from my master (https://github.com/asavartsov/mongoid_nested_set) please?

**Comment by shimotori** [comment]
@asavartsov I checked some cases and it seems fine. Thank you!

BTW, I found another issue regarding depth. I will send it soon.

**Comment by shimotori** [comment]
@asavartsov I found an issue on your modification as I mentioned in my previous comment.

When I set `identity_map_enabled = true` and add 3rd level node, its depth is set to 1.

(At the first time I found it, I thought it didn't relate to your modification, but on further investigation, I found it didn't occur on the current edge code (2ad8815).)

The current `spec_helper.rb` doesn't define `identity_map_enabled`, so it is set to `false`.

You can reproduce this with my above pull-requested specs and setting `identity_map_enabled = true` in `spec_helper.rb`.

**Comment by asavartsov** [comment]
Oh, I see. That could be easily fixed, but I would like to implement it in pure inc's so give me a bit more time.

**Comment by shimotori** [comment]
@asavartsov All right, thanks.

**Comment by asavartsov** [comment]
Okay, I implemented another moving algorithm to perform a move with consequential updates without any tricks but it requires to drop to driver level.

``` ruby
left, right     = [self[left_field_name], self[right_field_name]]
width, distance = [right - left + 1, bound - left]
edge            = bound > right ? bound - 1 : bound

# there would be no change
return self if left == edge || right == edge

# moving backwards
if distance < 0
  distance -= width
  left += width
end

scope_class.mongo_session.with(:safe => true) do |session|
  collection = session[scope_class.collection_name]
  scope = nested_set_scope.remove_order_by

  # allocate space for new move
  collection.find(
    scope.gte(left_field_name => bound).selector
  ).update_all("$inc" => { left_field_name => width })

  collection.find(
    scope.gte(right_field_name => bound).selector
  ).update_all("$inc" => { right_field_name => width })

  # move the nodes
  collection.find(
    scope.and(left_field_name => {"$gte" => left}, right_field_name => {"$lt" => left + width}).selector
  ).update_all("$inc" => { left_field_name => distance, right_field_name => distance })

  # remove the hole
  collection.find(
    scope.gt(left_field_name => right).selector
  ).update_all("$inc" => { left_field_name => -width })

  collection.find(
    scope.gt(right_field_name => right).selector
  ).update_all("$inc" => { right_field_name => -width })
end
```

What do you think, @blt04 ?

**Comment by blt04** [comment]
@asavartsov I think this looks good.   I think dropping to the driver level is fine.  It fixes the identity_map problem.

If you want to commit, I can pull from a pull request or just merge your master branch.

**Comment by shimotori** [comment]
I checked the edge (93866bb984) in my application and it seems fine. Thank you!
