### ISSUE TITLE
Feature request: Mongoid 3 support :)

### ISSUE THREAD

**Issue by kristianmandrup** [thinkwell/mongoid_nested_set#18]

**Comment by fklingler** [comment]
I think it's actually supported : 22f6ad1e926d876369edde2aa7c6b8efbe86642b f8d22d323052965f7d96d6de2b9a7df2b8218e7c

The version is bumped (e9120651350bf42e03231b2b9418c69adde58253), but this gem version doesn't seem to be published (actually 0.2.0 on [rubygems](http://rubygems.org/gems/mongoid_nested_set)).

Use `gem 'mongoid_nested_set', github: 'thinkwell/mongoid_nested_set'` in your Gemfile to use the latest version ;).

**Comment by blt04** [comment]
I pushed 0.2.1 to rubygems.
