### ISSUE TITLE
Issue while adding children in mongoid 3

### ISSUE THREAD

**Issue by mightylucene** [thinkwell/mongoid_nested_set#20]
Hi I am using this gem with mongoid  3.0.9 and mongoid_nested_set 0.2.1
I am getting following error while creating new node

Moped::Errors::OperationFailure: The operation: #<Moped::Protocol::Command
  @length=972
  @request_id=19
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="saverupiya_development.$cmd"
  @skip=0
  @limit=-1
  @selector={:mapreduce=>"categories", :map=>"\n          function() {\n            var agg = {\n              count: 1,\n              max: this.rgt,\n              min: this.rgt,\n              sum: this.rgt\n            };\n            emit(\"rgt\", agg);\n          }", :reduce=>"\n          function(key, values) {\n            var agg = { count: 0, max: null, min: null, sum: 0 };\n            values.forEach(function(val) {\n              if (val.max !== null) {\n                if (agg.max == null || val.max > agg.max) agg.max = val.max;\n                if (agg.min == null || val.max < agg.min) agg.min = val.max;\n                agg.sum += val.sum;\n              }\n              agg.count += 1;\n            });\n            return agg;\n          }", :query=>{}, :sort=>{"lft"=>1}, :out=>{:inline=>1}, :finalize=>"\n          function(key, agg) {\n            agg.avg = agg.sum / agg.count;\n            return agg;\n          }"}
  @fields=nil>
failed with error "db assertion failure"
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:74:in `block in command'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:532:in`[]'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:532:in `block (3 levels) in flush'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:531:in`map'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:531:in `block (2 levels) in flush'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:123:in`ensure_connected'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:527:in `block in flush'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:542:in`logging'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:526:in `flush'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:515:in`process'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:70:in `command'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/session/context.rb:51:in`block in command'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/session/context.rb:109:in `block in with_node'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/cluster.rb:203:in`block in with_primary'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/node.rb:168:in `ensure_primary'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/moped-1.2.7/lib/moped/cluster.rb:202:in`with_primary'
... 17 levels...
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/mongoid-3.0.9/lib/mongoid/persistence/insertion.rb:24:in `block in prepare'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:425:in`_run__3617450496681025951__save__2973861387003633222__callbacks'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in`_run_save_callbacks'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/mongoid-3.0.9/lib/mongoid/callbacks.rb:114:in`run_callbacks'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/mongoid-3.0.9/lib/mongoid/persistence/insertion.rb:23:in `prepare'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/mongoid-3.0.9/lib/mongoid/persistence/operations/insert.rb:26:in`persist'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/mongoid-3.0.9/lib/mongoid/persistence.rb:50:in `insert'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/mongoid-3.0.9/lib/mongoid/persistence.rb:79:in`save'
    from (irb):9
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in`start'
    from /home/loken/.rvm/gems/ruby-1.9.3-p194@global/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'1.9.3p194 :010

**Comment by shimotori** [comment]
Today I had the similar error when I tried to update Mongoid 3.0.4 to 3.0.11.

At first, I added indexes to lft and rgt, but this error still occurred.

Then I updated mongoid_nested_set to the edge version (d482b26428), and this error disappeared.

I hope this info helps you.

**Comment by galetahub** [comment]
Hi, 

I got this issue to mongoid_nested_set-0.2.1 and mongoid-3.0.16 (lates versions currently).
This commit fix issue - https://github.com/thinkwell/mongoid_nested_set/commit/d482b26428
Please push new gem version into rubygems.org.

Thanks
